version: 2.1
orbs:
  skedulo: skedulo/ci@0.5.5

parameters:
  image:
    default: skedulo/bottlerocket-admin-container
    type: string

workflows:
  everything:
    jobs:
      - skedulo/build_and_push_image:
          name: build_image_<<matrix.executor>>
          context:
            - aws-ecr
            - prisma
          matrix:
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          push: false
          use_buildkit: true
          extra_build_args: "--build-arg IMAGE_VERSION=${VERSION_TAG}"
          filters:
            branches:
              ignore:
                - skedulo-only

      - skedulo/build_and_push_image:
          name: build_and_push_image_<<matrix.executor>>
          context:
            - aws-ecr
            - prisma
          matrix:
            alias: build_and_push_image
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          use_buildkit: true
          extra_build_args: "--build-arg IMAGE_VERSION=${VERSION_TAG}"
          filters:
            branches:
              only:
                - skedulo-only

      - skedulo/create_and_push_manifest:
          name: create_and_push_manifest
          context: aws-ecr
          images: <<pipeline.parameters.image>>:${VERSION_TAG}-amd64,<<pipeline.parameters.image>>:${VERSION_TAG}-arm64
          manifest: <<pipeline.parameters.image>>
          requires:
            - build_and_push_image
