version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/install
      - run:
          name: "Login to ECR"
          command: |
            set -eu
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: "Build docker image"
          command: |
            set -eu
            IMAGE_NAME=${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1} make
      - deploy:
          name: "Upload container to registry"
          command: |
            set -eu
            VTAG="$(git describe --tags)"
            docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1}
            docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1} ${DOCKER_REGISTRY}/${DOCKER_REPO}:${VTAG}
            docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${VTAG}

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: aws-ecr
