version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy:
    docker:
      - image: cimg/python:3.8.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - aws-cli/install
      - run:
          name: "Login to ECR"
          command: |
            set -eu
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - deploy:
          name: "Upload container to registry"
          command: |
            set -eu
            VTAG="$(git describe --tags)"
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
            docker buildx build --push --platform linux/arm64/v8,linux/amd64 \
                    -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:${CIRCLE_SHA1} \
                    -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:${VTAG} .

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: aws-ecr
